#服务端口
server:
  port: 8003
#服务名称
spring:
  application:
    name: lpforum-provider-user
#关闭自我保护机制
eureka:
  server:
    enable-self-preservation: false
  #禁止服务本身去查找服务
  client:
    fetch-registry: true
    #禁止服务自己注册自己
    register-with-eureka: true
    #eureka注册地址
    service-url:
      defaultZone: http://localhost:8000/eureka/
  #eureka主机域名
  instance:
    hostname: localhost
    #应用列表的服务访问地址可以看到真实IP
    prefer-ip-address: true
    #页面应用列表服务status
    instance-id: lpforum-provider-user

#应用服务描述信息
info:
  app:
    name: ${spring.application.name}
  company:
    name: www.wdph.com
  build:
    artifactId: $project.artifactId$
    version: $project.version$