#开发环境eureka配置

#服务端口
server:
  port: 8050

#服务名称
spring:
  application:
    name: lpforum-config-client

eureka:
  #关闭自我保护机制
  server:
    enable-self-preservation: false
  #配置中心客户端检索服务
  client:
    fetch-registry: true
    #配置中心服务器注册服务
    register-with-eureka: true
    #eureka注册地址
    service-url:
      defaultZone: http://localhost:8000/eureka/
  #eureka域名
  instance:
    hostname: localhost
    #URL是否显示IP地址
    prefer-ip-address: true
    #服务注册的名称
    instance-id: lpforum-config-client

#服务健康信息
info:
  app:
    name: ${spring.application.name}
  company:
    name: www.wdph.com
  build:
    artifactId: $project.artifactId$
    version: $project.version$
