server:
  port: 8100
#服务名称
spring:
  application:
    name: lpforum-gateway
  cloud:
    gateway:
      routes:
      - id: after_route
        uri: http://httpbin.org:80/get
        predicates:
        - After=2017-01-20T17:42:47.789-07:00[America/Denver]
        filters:
        -
#关闭自我保护机制
eureka:
  server:
    enable-self-preservation: false
  #到注册中心检索服务
  client:
    fetch-registry: true
    #注册到注册中心
    register-with-eureka: true
    #eureka注册中心地址
    service-url:
      defaultZone: http://localhost:8000/eureka/
  #eureka域名
  instance:
    hostname: localhost
    #URL是否显示IP地址
    prefer-ip-address: true
    #服务显示名称
    instance-id: lpforum-consumer-user

#服务详细信息
info:
  app:
    name: ${spring.application.name}
  company:
    name: www.wdph.com
  build:
    artifactId: $project.artifactId$
    version: $project.version$

#feign开启熔断器
#feign:
#  hystrix:
#   enabled: true